### ISSUE TITLE
Gefühlt Jeder 3. Skill kann manchmal nicht gecastet werden (Timkoe Barbar meistens Aufstampfen)

### ISSUE THREAD

**Issue by Timkoe** [LostKingdoms/Lost-Kingdoms-IssueTracker#254]
![Unbenannt](https://user-images.githubusercontent.com/55351056/77805277-c8ca1380-7081-11ea-94c3-a7de67691b36.PNG)

**Comment by Timkoe** [comment]
Spieler kann bei diesem fehler keinen anvisieren.

**Comment by TimK1998** [comment]
java.lang.NullPointerException: null
	at de.lostkingdoms.core.entities.user.User.isFriendly(User.java:731) ~[?:?]
	at de.lostkingdoms.core.entities.classsystem.skill.classes.barbar.Axtwurf$1$1.run(Axtwurf.java:58) ~[?:?]
	at de.lostkingdoms.core.utils.scheduler.Scheduler$3$1.run(Scheduler.java:211) ~[?:?]
	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:64) ~[patched_1.12.2.jar:git-Paper-1618]
	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:423) ~[patched_1.12.2.jar:git-Paper-1618]
	at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:840) ~[patched_1.12.2.jar:git-Paper-1618]
	at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:423) ~[patched_1.12.2.jar:git-Paper-1618]
	at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:774) ~[patched_1.12.2.jar:git-Paper-1618]
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:666) ~[patched_1.12.2.jar:git-Paper-1618]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_211]
[00:44:22] [Server thread/WARN]: [lostkingdomscore] Task #13318 for lostkingdomscore v0.1 generated an exception
