### ISSUE TITLE
Bärenfalle despawnt nicht

### ISSUE THREAD

**Issue by Tysaby** [LostKingdoms/Lost-Kingdoms-IssueTracker#306]
Bärenfalle despawnt nicht über zeit und manchmal (nicht reproduzierbar bisher vll server restart oder sprengung?) nicht wenn eine neue gesetzt wird. Beide Fallen können noch ausgelöst werden

**Comment by Kyraja** [comment]
Folgendes Szenario:

Der Spieler setzt eine Falle, loggt sich dann aus, dann placed er eine neue Falle (erste bleibt bestehen) und hat dadurch 2 Redstone die aktiv sind...

Wenn er sich nicht ausloggt, sondern direkt placed, dann wird das erste Redstone entfernt.


java.util.ConcurrentModificationException: null
	at java.util.HashMap$HashIterator.nextNode(HashMap.java:1445) ~[?:1.8.0_242]
	at java.util.HashMap$EntryIterator.next(HashMap.java:1479) ~[?:1.8.0_242]
	at java.util.HashMap$EntryIterator.next(HashMap.java:1477) ~[?:1.8.0_242]
	at de.lostkingdoms.core.entities.classsystem.skill.classes.waldlaeufer.Baerenfalle$1.run(Baerenfalle.java:48) ~[?:?]
	at de.lostkingdoms.core.utils.scheduler.Scheduler$1.run(Scheduler.java:160) ~[?:?]
	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:64) ~[patched_1.12.2.jar:git-Paper-1618]
	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:423) ~[patched_1.12.2.jar:git-Paper-1618]
	at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:840) ~[patched_1.12.2.jar:git-Paper-1618]
	at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:423) ~[patched_1.12.2.jar:git-Paper-1618]
	at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:774) ~[patched_1.12.2.jar:git-Paper-1618]
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:666) ~[patched_1.12.2.jar:git-Paper-1618]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_242]

**Comment by Kyraja** [comment]
Fehler 2: 

Wenn die Falle gesprengt wird und dann eine neue Falle gesetzt wird, dann kann der User die erste Falle abbauen.
